services:
  mongodb:
    image: mongo:latest
    container_name: mongodb

    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root_user
      MONGOINITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db

    restart: unless-stopped

volumes:
  mongo_data:
    driver: local
